config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :my_items, controller: 'user_items', only: %i[index destroy] do
    collection do
      get 'recipes'
    end
  end
  post 'my_items(/:item_id)', to: 'user_items#create'
  delete 'my_items/:id', to: 'user_items#destroy'
  get 'stores/results', to: 'stores#results'
end

app/models/store.rb
class Store < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :store_items
  has_many :items, through: :store_items

  validates :name, :address, presence: true

  # def self.nearby(latitude, longitude, distance_in_kms = 50)
  def self.nearby(latitude, longitude, distance_in_kms)
    near([latitude, longitude], distance_in_kms, units: :km)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def results
    @item_ids = params[:list]
    totals = {}
    Store.all.each do |store|
      store_items = StoreItem.where(item_id: @item_ids, store_id: store.id)
      totals[store.name] = store_items.map(&:price).sum
    end

    @total_by_store = totals.map do |name, sum|
      { store: name, total_price: sum }
    end
    @total_by_store.sort_by! { |hash| hash[:total_price] }
    number_of_stores = @total_by_store.length
    @total_by_store.each.with_index{|h, i| h[:category] = categorize(i, number_of_stores - 1) }

    @stores = if params[:latitude].present? && params[:longitude].present?
                Store.nearby(params[:latitude], params[:longitude])
              else
                Store.all
              end
            @markers = @stores.geocoded.map do |store|
              store_total = @total_by_store.select{|h| h[:store] == store.name}.first.dig(:total_price)
              price_category = @total_by_store.select{|h| h[:store] == store.name}.first.dig(:category)
                {
                  lat: store.latitude,
                  lng: store.longitude,
                  info_window_html: render_to_string(partial: "info_window", locals: { store: store, store_total: store_total, price_category: price_category}),
                  price_category: price_category,
                }
            end
    authorize @stores
  end


  def categorize(index, last_item)
    case index
    when 0
      "cheapest"
    when 1...last_item
      "affordable"
    when last_item
      "expensive"
    end
  end
end


private

  def price_category(store_total)
    if store_total == @total_by_store.first[:total_price]
      cheapest = store_total
    elsif store_total == @total_by_store.last[:total_price]
      expensive = store_total
    else
      affordable = store_total
    end
    { cheapest: cheapest,
      expensive: expensive,
      mid_range: affordable }
  end

  # def exists?(value)
  #   value if value
  # end

app/views/stores/_info_window.html.erb
<div class="store-container">
    <img class="popup-image" src="<%= store.image_url%>" alt="Store image">


  <div class="card-info">
      <div class="store-category">
        <div class="title">
          <h2><%= store.name %></h2>
        </div>

        <% if price_category == "cheapest" %>
          <button type="button" class="background-green button-outline" disabled>$</button>

        <% elsif price_category == "affordable" %>
          <button type="button" class="background-blue button-outline" disabled>$$</button>

        <% elsif price_category == "expensive" %>
            <button type="button" class="background-red button-outline" disabled>$$$</button>

        <% end %>

      </div>


    <div class="store-info">
      <p><%= store.address %></p>
    </div>

    <p class="result">Total List Price:  <strong class="price">$<%= store_total %></strong>

  </div>
</div>

app/views/stores/results.html.erb
<%# <div> %>
  <%# <% @total_by_store.each do |h| %>
    <%# <div> %>
      <%# <h2><%= h[:store]</h2>  %>
      <%# <p>Total List Price of Items: $<%= h[:total_price]</p>  %>
    <%# </div> %>
  <%# <% end %>
<%# </div> %>
<div style= "position:relative">

  <%= link_to my_items_path, class:"back-button" do %>
      <i class="fa-solid fa-arrow-left fa-border fa-2x"></i>
  <% end %>


 <div class="card-legend">
  <button type="button" class="background-green button-outline round-button" disabled>$</button>
  <button type="button" class="background-blue button-outline round-button" disabled>$$</button>
  <button type="button" class="background-red button-outline round-button" disabled>$$$</button>
 </div>


  <div style="width: 100%; height: 100vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>