config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :my_items, controller: 'user_items', only: %i[index destroy] do
    collection do
      get 'recipes'
    end
  end
  post 'my_items(/:item_id)', to: 'user_items#create'
  delete 'my_items/:id', to: 'user_items#destroy'
  get 'stores/results', to: 'stores#results'
end

app/models/store.rb
class Store < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :store_items
  has_many :items, through: :store_items

  validates :name, :address, presence: true

  # def self.nearby(latitude, longitude, distance_in_kms = 50)
  def self.nearby(latitude, longitude, distance_in_kms)
    near([latitude, longitude], distance_in_kms, units: :km)
  end
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :user_id, :item_id, presence: true
end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  def index
    @user_items = policy_scope(UserItem)
    @items = policy_scope(Item)
    @stores = policy_scope(Store)
    @item_ids = @user_items.map(&:item_id)

    if params[:query].present?
      @items = Item.search_by_name(params[:query])
      query_api if @items.empty?
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'results', locals: { items: @items }, formats: [:html] }
    end
  end

  def create
    @user_item = UserItem.new
    @user_item.user = current_user
    @user_item.item = Item.find(params[:item_id])
    authorize @user_item
    redirect_to my_items_path, notice: 'Item added successfully.' if @user_item.save!
  end

  def destroy
    @user_item = UserItem.find(params[:id])
    authorize @user_item
    @user_item.destroy
    redirect_to my_items_path, status: :see_other
  end

  def recipes
    @user_items = UserItem.where(user_id: current_user.id)
    @recipes_list = recipes_list(@user_items)
    process_recipes(@recipes_list)
    authorize @user_items
  end

  private

  def query_api
    url = "https://api.edamam.com/api/food-database/v2/parser?app_id=#{ENV.fetch('EDAMAM_RECIPE_API_APP_ID')}&app_key=#{ENV.fetch('EDAMAM_RECIPE_API_KEY')}&ingr=#{params[:query]}"
    response = URI.open(url).read
    json = JSON.parse(response)
    json['hints'].each do |item|
      unless Item.find_by(food_id: item.dig('food', 'foodId'))
        food_name = item.dig('food', 'label')
        food_id = item.dig('food', 'foodId')
        new_item = Item.create!({ name: food_name.downcase, food_id: food_id })
        add_store_item(new_item)
      end
    end
  end

  def add_store_item(new_item)
    price_offset = (-3.0..3.0).step(0.75).to_a.reverse
    price_offset.delete_if { |element| element.zero? }
    Store.all.each_with_index do |store, index|
      dollars = (5.0..15.0).step(1).to_a.sample
      cents = ((50.0..70.0).step(10).to_a.sample + 9.0) / 100
      StoreItem.create!(
        store_id: store.id,
        item_id: new_item.id,
        price: (dollars + cents + price_offset[index]).round(2)
      )
    end
  end

  def recipes_list(user_items)
    ingredients = []
    user_items.each do |user_item|
      ingredients << Item.find(user_item.item_id).name
    end
    client = OpenAI::Client.new
    response = client.chat(parameters: {
      model: "gpt-3.5-turbo",
      messages: [{
        role: "user",
        content: "Provide a recipe based on the following ingredients: #{ingredients.join}, the recipe should follow this specific format

        1. [Recipe's Name]

        - [Quantity] [Ingredient]
        - [Quantity] [Ingredient]
        - [Quantity] [Ingredient]

        2. [Write the instructions in one paragraph.]"
      }]
    })
    response["choices"][0]["message"]["content"]
  end

  def process_recipes(recipes_list)
    current_recipe = { name: "", ingredients: [], instructions: "" }

    recipes_list.lines.each do |line|
      next if line.length.zero?

      if line.start_with?(/1\.\s/)
        current_recipe[:name] = line.sub("1. ", "").strip
      elsif line.start_with?(/-\s/)
        current_recipe[:ingredients] << line.sub("- ", "").strip
      elsif line.start_with?(/2\.\s/)
        current_recipe[:instructions] << line.sub("2. ", "").strip
      end
    end

    @name = current_recipe[:name]
    @ingredients = current_recipe[:ingredients]
    @instructions = current_recipe[:instructions]
  end
end

app/views/user_items/_demo_day_recipe.html.erb
<%# Demo day view %>

<%# <div class="my-items-container" data-controller="toggle-empty-message">

  <h1 class="text-center">Recipe Idea</h1>

  <div class="recipe-container">
    <h4>Chicken Pesto Penne</h4>
    <p><strong>Ingredients:</strong></p>
    <ul>
      <li>2 chicken breasts</li>
      <li>12 oz penne pasta</li>
      <li>1 cup grated parmesan cheese</li>
  </ul>
    <p><strong>Instructions:</strong></p>
    <p>    Start by cooking the penne pasta according to package instructions. While the pasta is cooking, season the chicken breasts with salt and pepper and cook in a skillet over medium heat until fully cooked. Once cooked, slice the chicken into strips. In a separate large skillet, combine the cooked penne pasta, sliced chicken, and pesto sauce. Mix well to coat everything evenly. Finally, sprinkle the grated parmesan cheese over the top and stir until melted. Serve hot and enjoy your delicious Chicken Pesto Penne!</p>
  </div>

  <div class="find-deals-button-container">
    <%= link_to 'My Grocery List', my_items_path(list: @recipe_ids), class: 'generate-recipe-button btn btn-primary' %>
  <%# </div> %>

<%# </div> %>

app/views/user_items/_form.html.erb
<div data-controller="search-items">
  <%= simple_form_for my_items_path, data: { search_items_target: 'form' }, html: { class: 'search-form' } do |f| %>
    <div class="search-bar">
      <div class="search-input input-group-prepend">
        <%= f.input :name, label: false, placeholder: "Add items to your list", value: params[:name],
         input_html: { class: 'search-input rounded-pill',
         data: { search_items_target: 'input', action: 'keyup->search-items#results' } } %>
         <i class="fa-solid fa-magnifying-glass"></i>
      <span class="close-icon">&#10006;</span>
      </div>
    </div>
    <%= render "results" %>
  <% end %>
</div>

app/views/user_items/_results.html.erb
<div data-search-items-target='results'>
  <% unless params[:query].blank? %>
    <ul class='list-group'>
      <% @items.each do |item| %>
        <li class='list-group-item'>
          <%= item.name %>
          <%= link_to 'Add item', my_item_path(item), data: { turbo_method: :post } %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/user_items/index.html.erb
<div class="my-items-container" data-controller="search-items">
  <h1 class="text-center">Grocery List</h1>
  <div>
    <%= simple_form_for my_items_path, method: :get, data: { search_items_target: 'form' }, html: { class: 'search-form' } do %>
      <div class="search-bar" data-search-items-target="bar">
        <input class="form-control search-input"
               data-search-items-target="input"
               data-action="keyup->search-items#results"
               placeholder="Add Items"
               type="text"
               name="query"
               id="search_query">
        <i class="fas fa-search fa-magnifying-glass" data-action="click->search-items#submitForm" aria-hidden="true"></i>
      </div>
      <div class="search-results" id="search-results" data-search-items-target="results">
        <%= render "results" %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col">
      <div class="cards" id="items-list" data-search-items-target="itemsList">
        <% @user_items.each do |user_item| %>
          <div class="card-body list-group-item" data-item-id="<%= user_item.id %>">
            <input type="checkbox" class="item-checkbox" data-action="change->search-items#toggleEmptyMessage">
            <h5 class="card-title text-start"><%= user_item.item.name %>
              <%= link_to my_item_path(user_item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "delete-link" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </h5>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% if @user_items.empty? %>
    <div id="empty-message" class="empty-list-message">
      <div class="empty-message-content">
        <div class="empty-image"></div>
        Your shopping list is empty!
      </div>
    </div>
  <% end %>
  <% if @user_items.any? %>
    <div class="find-deals-button-container">
      <%= link_to 'Find Best Deals', stores_results_path(list: @item_ids), class: 'find-deals-button btn btn-primary' %>
      <%= link_to 'Generate Recipe', recipes_my_items_path(list: @recipe_ids), class: 'generate-recipe-button btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/user_items/recipes.html.erb
<%# To render the demo day view %>
<%# <%= render 'demo_day_recipe' %>

<div class="my-items-container" data-controller="toggle-empty-message">

  <h1 class="text-center">Recipe Idea</h1>

  <div class="recipe-container">
    <h4><%= @name %>
    <%# <img src="" alt="Recipe Image"> %>
    <p><strong>Ingredients:</strong></p>
    <ul>
      <% @ingredients.each do |ingredient| %>
    <li><%= ingredient %>
      <% end %>
    </ul>
    <p><strong>Instructions:</strong></p>
    <p><%= @instructions %>
  </div>

  <div class="find-deals-button-container">
    <%= link_to 'My Grocery List', my_items_path(list: @recipe_ids), class: 'generate-recipe-button btn btn-primary' %>
  </div>

</div>

<%# For testing Chat GPT results %>
<%# <% @recipes_list.lines.each do |line| %>
  <%# <%= tag.p line.chomp %>
<%# <% end %>